server:
    port: 8080
eureka:
  client:
     service-url:
        defaultZone: http://localhost:8761/eureka/

spring:
    application:
        name: customer
    datasource:
        password: 'admin'
        url: jdbc:postgresql://localhost:5432/customer
        username: 'admin'
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
